import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, "../../data");

// ── Types ─────────────────────────────────────────────────────────────────────

export interface Transaction {
  id: string;
  type: "sale" | "purchase";
  productName: string;
  productType: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  totalAmount: number;
  gstPercent: number;
  gstAmount: number;
  grandTotal: number;
  sellerName: string;
  sellerLocation: string;
  buyerName: string;
  buyerLocation: string;
  transportProvider: string;
  transportCost: number;
  invoiceNumber: string;
  date: string;
  status: "completed" | "pending" | "cancelled";
}

// ── GST Rate Lookup ───────────────────────────────────────────────────────────

const GST_RATES: Record<string, number> = {
  fmcg: 12,
  agri: 5,
  textiles: 5,
  pharma: 12,
  electronics: 18,
  handicrafts: 12,
  general: 18,
};

// ── Persistence ───────────────────────────────────────────────────────────────

function loadTransactions(): Transaction[] {
  return JSON.parse(readFileSync(join(DATA_DIR, "transactions.json"), "utf-8"));
}

function saveTransactions(txns: Transaction[]): void {
  writeFileSync(join(DATA_DIR, "transactions.json"), JSON.stringify(txns, null, 2), "utf-8");
}

// ── Core Logic (exported for orchestrator) ────────────────────────────────────

export function generateInvoiceLogic(params: {
  type: "sale" | "purchase";
  productName: string;
  productType: string;
  category: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  sellerName: string;
  sellerLocation: string;
  buyerName: string;
  buyerLocation: string;
  transportProvider: string;
  transportCost: number;
}): { invoice: Transaction; invoiceText: string } {
  const txns = loadTransactions();
  const seqNum = txns.length + 1;
  const invoiceNumber = `ANV-2026-${String(seqNum).padStart(4, "0")}`;
  const id = `TXN-${String(seqNum).padStart(3, "0")}`;

  const totalAmount = Math.round(params.quantity * params.unitPrice * 100) / 100;
  const gstPercent = GST_RATES[params.category] ?? GST_RATES["general"];
  const gstAmount = Math.round(totalAmount * (gstPercent / 100) * 100) / 100;
  const grandTotal = Math.round((totalAmount + gstAmount + params.transportCost) * 100) / 100;

  const invoice: Transaction = {
    id,
    type: params.type,
    productName: params.productName,
    productType: params.productType,
    quantity: params.quantity,
    unit: params.unit,
    unitPrice: params.unitPrice,
    totalAmount,
    gstPercent,
    gstAmount,
    grandTotal,
    sellerName: params.sellerName,
    sellerLocation: params.sellerLocation,
    buyerName: params.buyerName,
    buyerLocation: params.buyerLocation,
    transportProvider: params.transportProvider,
    transportCost: params.transportCost,
    invoiceNumber,
    date: new Date().toISOString(),
    status: "completed",
  };

  const invoiceText = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                  TAX INVOICE
               ${invoiceNumber}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Date:             ${new Date().toLocaleDateString("en-IN")}
Type:             ${params.type.toUpperCase()}

SELLER
  Name:           ${params.sellerName}
  Location:       ${params.sellerLocation}

BUYER
  Name:           ${params.buyerName}
  Location:       ${params.buyerLocation}

──────────────────────────────────────────────────────
ITEM DETAILS
──────────────────────────────────────────────────────
  Product:        ${params.productName} (${params.productType})
  Quantity:       ${params.quantity} ${params.unit}
  Unit Price:     ₹${params.unitPrice}
  Subtotal:       ₹${totalAmount.toLocaleString("en-IN")}

──────────────────────────────────────────────────────
TAX DETAILS
──────────────────────────────────────────────────────
  GST (${gstPercent}%):     ₹${gstAmount.toLocaleString("en-IN")}
  Transport:      ₹${params.transportCost.toLocaleString("en-IN")}

══════════════════════════════════════════════════════
  GRAND TOTAL:    ₹${grandTotal.toLocaleString("en-IN")}
══════════════════════════════════════════════════════

  Status: ✅ COMPLETED
  Generated by Anvaya Business Platform
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`.trim();

  return { invoice, invoiceText };
}

export function logTransactionLogic(invoice: Transaction): { logged: boolean; message: string } {
  const txns = loadTransactions();
  txns.push(invoice);
  saveTransactions(txns);
  return {
    logged: true,
    message: `✅ Transaction ${invoice.invoiceNumber} logged to ledger. Type: ${invoice.type}, Product: ${invoice.productName}, Grand Total: ₹${invoice.grandTotal}`,
  };
}

export function getTransactionHistoryLogic(filters?: {
  type?: "sale" | "purchase";
  productName?: string;
  sellerLocation?: string;
}): { transactions: Transaction[]; summary: { totalSales: number; totalPurchases: number; netRevenue: number } } {
  const all = loadTransactions();
  let filtered = all;

  if (filters?.type) filtered = filtered.filter(t => t.type === filters.type);
  if (filters?.productName) {
    filtered = filtered.filter(t =>
      t.productName.toLowerCase().includes(filters.productName!.toLowerCase())
    );
  }
  if (filters?.sellerLocation) {
    filtered = filtered.filter(t =>
      t.sellerLocation.toLowerCase().includes(filters.sellerLocation!.toLowerCase())
    );
  }

  const totalSales = filtered
    .filter(t => t.type === "sale")
    .reduce((s, t) => s + t.grandTotal, 0);
  const totalPurchases = filtered
    .filter(t => t.type === "purchase")
    .reduce((s, t) => s + t.grandTotal, 0);

  return {
    transactions: filtered,
    summary: {
      totalSales: Math.round(totalSales * 100) / 100,
      totalPurchases: Math.round(totalPurchases * 100) / 100,
      netRevenue: Math.round((totalSales - totalPurchases) * 100) / 100,
    },
  };
}

// ── MCP Tool Registrations ────────────────────────────────────────────────────

export function registerBusinessDocumentTools(server: McpServer): void {
  server.tool(
    "generateInvoice",
    "Generate a full tax invoice (GST) for a sale or purchase. Calculates tax based on product category, adds transport cost, and produces a formatted invoice document.",
    {
      type: z.enum(["sale", "purchase"]).describe("Transaction type"),
      productName: z.string().describe("Product name"),
      productType: z.string().describe("Product type (standard/perishable/fragile/hazardous)"),
      category: z.string().describe("Product category (fmcg, agri, textiles, pharma, electronics, handicrafts, general)"),
      quantity: z.number().describe("Quantity being sold/purchased"),
      unit: z.string().describe("Unit (kg, pieces, rolls, etc.)"),
      unitPrice: z.number().describe("Price per unit in INR"),
      sellerName: z.string().describe("Seller's business name"),
      sellerLocation: z.string().describe("Seller's city/location"),
      buyerName: z.string().describe("Buyer's business name"),
      buyerLocation: z.string().describe("Buyer's city/location"),
      transportProvider: z.string().optional().default("Self").describe("Transport provider name"),
      transportCost: z.number().optional().default(0).describe("Transport cost in INR"),
    },
    async (params) => {
      const result = generateInvoiceLogic({
        type: params.type,
        productName: params.productName,
        productType: params.productType,
        category: params.category,
        quantity: params.quantity,
        unit: params.unit,
        unitPrice: params.unitPrice,
        sellerName: params.sellerName,
        sellerLocation: params.sellerLocation,
        buyerName: params.buyerName,
        buyerLocation: params.buyerLocation,
        transportProvider: params.transportProvider ?? "Self",
        transportCost: params.transportCost ?? 0,
      });
      return { content: [{ type: "text", text: result.invoiceText + "\n\n" + JSON.stringify(result.invoice, null, 2) }] };
    }
  );

  server.tool(
    "logTransaction",
    "Log a completed transaction to the persistent ledger (data/transactions.json). Automatically called after invoice generation for record-keeping and tax reporting.",
    {
      invoice: z.object({
        id: z.string(),
        type: z.enum(["sale", "purchase"]),
        productName: z.string(),
        productType: z.string(),
        quantity: z.number(),
        unit: z.string(),
        unitPrice: z.number(),
        totalAmount: z.number(),
        gstPercent: z.number(),
        gstAmount: z.number(),
        grandTotal: z.number(),
        sellerName: z.string(),
        sellerLocation: z.string(),
        buyerName: z.string(),
        buyerLocation: z.string(),
        transportProvider: z.string(),
        transportCost: z.number(),
        invoiceNumber: z.string(),
        date: z.string(),
        status: z.enum(["completed", "pending", "cancelled"]),
      }).describe("The full invoice/transaction object to log"),
    },
    async ({ invoice }) => {
      const result = logTransactionLogic(invoice as Transaction);
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    }
  );

  server.tool(
    "getTransactionHistory",
    "Retrieve transaction history with optional filters. Returns all logged transactions plus a summary of total sales, purchases, and net revenue.",
    {
      type: z.enum(["sale", "purchase"]).optional().describe("Filter by transaction type"),
      productName: z.string().optional().describe("Filter by product name"),
      sellerLocation: z.string().optional().describe("Filter by seller location"),
    },
    async ({ type, productName, sellerLocation }) => {
      const result = getTransactionHistoryLogic({ type, productName, sellerLocation });
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    }
  );
}
